server:
    # eureka server 의해서 임의의 port가 할당(spring server)
  port: 0

  
# eureka client user service -> eureka server
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/

spring:
    rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

    # mariadb settings
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3306/inspire  
        username: root
        password: myky0226@
    
    jpa:
        database: mariadb 
        # create, create-drop, update, none
        database-platform: org.hibernate.dialect.H2Dialect    
        hybernate:
            ddl-auto: create
        # 콘솔출력
        show-sql: true     
        
    data:
        redis:
            host: localhost
            port: 6379
            password: 
            timeout: 6000ms

    cloud:
        bus:
            enabled: true